---
title: "AOC1"
format: html
editor: source
---

## Packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(stringi)
```

## Data

```{r message=FALSE, warning=FALSE}
aoc1 = read_csv("aoc1.txt", col_names = "v1")
```

## Part 1

```{r}
aoc1 %>% 
  mutate(v2 = gsub("[^\\d]+", "", v1, perl=TRUE) %>% as.numeric) %>% 
  mutate(start = str_sub(v2, 1, 1), 
         end = str_sub(v2, -1, -1)) %>% 
  mutate(v3 = str_c(start, end) %>% as.numeric()) %>% 
  summarise(sum(v3))

```

## Part 2

```{r}
numb_replacements =
  c("one" = "1",
    "two" = "2",
    "three" = "3",
    "four" = "4",
    "five" = "5",
    "six" = "6",
    "seven" = "7",
    "eight" = "8",
    "nine" = "9"
  ) 

numb_replacements_reverse = numb_replacements
names(numb_replacements_reverse) = names(numb_replacements_reverse) %>% stri_reverse()
numb = names(numb_replacements) %>% paste(collapse = "|")
numb_reverse = names(numb_replacements_reverse) %>% paste(collapse = "|")

words2numbers = function(x, reverse = FALSE){
  if(!reverse){
    str_replace_all(x, numb_replacements)
  } else {
    str_replace_all(x, numb_replacements_reverse)
  }
}

aoc1 %>% 
  mutate(v1_f = str_replace_all(v1, numb, words2numbers)) %>% 
  mutate(v1_r = str_replace_all(stri_reverse(v1), numb_reverse, 
                                ~ words2numbers(.x, reverse = TRUE))) %>% 
  mutate(v2_f = gsub("[^\\d]+", "", v1_f, perl=TRUE) %>% as.numeric) %>% 
  mutate(v2_r = gsub("[^\\d]+", "", v1_r, perl=TRUE) %>% as.numeric) %>% 
  mutate(start = str_sub(v2_f, 1, 1), 
         end = str_sub(v2_r, 1, 1)) %>% 
  mutate(v3 = str_c(start, end) %>% as.numeric()) %>% 
  summarise(sum(v3))
```
